export const shopDataActionTypes = {
    GET_SHOP_DATA: "GET_SHOP_DATA",
    FETCH_SHOP_DATA_START: "FETCH_SHOP_DATA_START",
    FETCH_SHOP_DATA_SUCCESS: "FETCH_SHOP_DATA_SUCCESS",
    FETCH_SHOP_DATA_FAILURE: "FETCH_SHOP_DATA_FAILURE",
};
