export const shopDataActionTypes = {
    FETCH_SHOP_DATA_START: "FETCH_SHOP_DATA_START",
    FETCH_SHOP_DATA_SUCCESS: "FETCH_SHOP_DATA_SUCCESS",
    FETCH_SHOP_DATA_FAILURE: "FETCH_SHOP_DATA_FAILURE",

    FETCH_CURRENT_ITEM_TITLE: "FETCH_CURRENT_ITEM_TITLE",

    FETCH_DELETE_PRODUCT_CATEGORY_START: "FETCH_DELETE_PRODUCT_CATEGORY_START",
    FETCH_DELETE_PRODUCT_CATEGORY_SUCCESS:
        "FETCH_DELETE_PRODUCT_CATEGORY_SUCCESS",
    FETCH_DELETE_PRODUCT_CATEGORY_FAILURE:
        "FETCH_DELETE_PRODUCT_CATEGORY_FAILURE",

    FETCH_ADD_NEW_SHOP_CATEGORY_START: "FETCH_ADD_NEW_SHOP_CATEGORY_START",
    FETCH_ADD_NEW_SHOP_CATEGORY_SUCCESS: "FETCH_ADD_NEW_SHOP_CATEGORY_SUCCESS",
    FETCH_ADD_NEW_SHOP_CATEGORY_FAILURE: "FETCH_ADD_NEW_SHOP_CATEGORY_FAILURE",
};
