export const shopDataActionTypes = {
    GET_SHOP_DATA: "GET_SHOP_DATA",
    FETCH_SHOP_DATA_START: "FETCH_SHOP_DATA_START",
    FETCH_SHOP_DATA_SUCCESS: "FETCH_SHOP_DATA_SUCCESS",
    FETCH_SHOP_DATA_FAILURE: "FETCH_SHOP_DATA_FAILURE",
    FETCH_CURRENT_ITEM_TITLE: "FETCH_CURRENT_ITEM_TITLE",
    FETCH_DELETE_PRODUCT_CATEGORY_START: "FETCH_DELETE_PRODUCT_CATEGORY_START",
    FETCH_DELETE_PRODUCT_CATEGORY_SUCCESS:
        "FETCH_DELETE_PRODUCT_CATEGORY_SUCCESS",
    FETCH_DELETE_PRODUCT_CATEGORY_FAILURE:
        "FETCH_DELETE_PRODUCT_CATEGORY_FAILURE",
};
