export const productItemActionTypes = {
    FETCH_PRODUCT_ITEM_START: "FETCH_PRODUCT_ITEM_START",
    FETCH_PRODUCT_ITEM_SUCCESS: "FETCH_PRODUCT_ITEM_SUCCESS",
    FETCH_PRODUCT_ITEM_FAILURE: "FETCH_PRODUCT_ITEM_FAILURE",
};
