export const productItemActionTypes = {
    FETCH_PRODUCT_ITEM_START: "FETCH_PRODUCT_ITEM_START",
    FETCH_PRODUCT_ITEM_SUCCESS: "FETCH_PRODUCT_ITEM_SUCCESS",
    FETCH_PRODUCT_ITEM_FAILURE: "FETCH_PRODUCT_ITEM_FAILURE",

    FETCH_CURRENT_ITEM_ID_START: "FETCH_CURRENT_ITEM_ID_START",
    FETCH_CURRENT_ITEM_ID_SUCCESS: "FETCH_CURRENT_ITEM_ID_SUCCESS",
    FETCH_CURRENT_ITEM_ID_FAILURE: "FETCH_CURRENT_ITEM_ID_FAILURE",

    FETCH_ADD_NEW_PRODUCT_ITEM_START: "FETCH_ADD_NEW_PRODUCT_ITEM_START",
    FETCH_ADD_NEW_PRODUCT_ITEM_SUCCESS: "FETCH_ADD_NEW_PRODUCT_ITEM_SUCCESS",
    FETCH_ADD_NEW_PRODUCT_ITEM_FAILURE: "FETCH_ADD_NEW_PRODUCT_ITEM_FAILURE",

    FETCH_UPDATE_PRODUCT_ITEM_START: "FETCH_UPDATE_PRODUCT_ITEM_START",
    FETCH_UPDATE_PRODUCT_ITEM_SUCCESS: "FETCH_UPDATE_PRODUCT_ITEM_SUCCESS",
    FETCH_UPDATE_PRODUCT_ITEM_FAILURE: "FETCH_UPDATE_PRODUCT_ITEM_FAILURE",
};
