export const productItemActionTypes = {
    FETCH_PRODUCT_ITEM_START: "FETCH_PRODUCT_ITEM_START",
    FETCH_PRODUCT_ITEM_SUCCESS: "FETCH_PRODUCT_ITEM_SUCCESS",
    FETCH_PRODUCT_ITEM_FAILURE: "FETCH_PRODUCT_ITEM_FAILURE",
    FETCH_CURRENT_ITEM_ID_START: "FETCH_CURRENT_ITEM_ID_START",
    FETCH_CURRENT_ITEM_ID_SUCCESS: "FETCH_CURRENT_ITEM_ID_SUCCESS",
    FETCH_CURRENT_ITEM_ID_FAILURE: "FETCH_CURRENT_ITEM_ID_FAILURE",
};
