export const clientListActionTypes = {
    FETCH_CLIENT_LIST_START: "FETCH_CLIENT_LIST_START",
    FETCH_CLIENT_LIST_SUCCESS: "FETCH_CLIENT_LIST_SUCCESS",
    FETCH_CLIENT_LIST_FAILURE: "FETCH_CLIENT_LIST_FAILURE",
};
