# GET ALL PRODUCT DATA
GET http://localhost:8000/v1/products

###

# get all product category for a user
POST http://localhost:8000/v1/products
content-type: application/json

{
    "userId": "113577393364732277603"
}

###

# create new product category 
POST http://localhost:8000/v1/products/createProduct
content-type: application/json

{
    "userId":"113577393364732277603",
    "product": "category2"
}

###

# get all product items for a user
POST  http://localhost:8000/v1/productItem/
content-type: application/json

{
    "userId": "113577393364732277603"
}

###

# create new productItem
POST http://localhost:8000/v1/productItem/createProductItem
content-type: application/json

{
    "userId": "113577393364732277603",
    "ProductCategoryId":"61603f0ee3599f729fbef893",
    "itemName": "item 2",
    "imageUrl": "item 2",   
    "price": 123
}

###

PUT http://localhost:8000/v1/productItem/updateProductItem
content-type: application/json

{
    "itemToUpdate": "615daeb07b17d504c37ba082",
    "userId": "113577393364732277603",
    "ProductCategoryId":"615daef97b17d504c37ba08b",
    "itemName": "update1",
    "imageUrl": "update1",   
    "price": 123
}

###




