# GET ALL PRODUCT DATA
GET http://localhost:8000/v1/products

###

# get all product category for a user
POST http://localhost:8000/v1/products
content-type: application/json

{
    "userId": "113577393364732277603"
}

###

# create new product category 
POST http://localhost:8000/v1/products/createProduct
content-type: application/json

{
    "userId":"113577393364732277603",
    "product": "category2"
}

###

# Delete product category
DELETE  http://localhost:8000/v1/products/deleteCategoryItem
content-type: application/json

{
    "itemToDelete": "6161ff54be549b1fc8bccef8"
}

###

# get all product items for a user
POST  http://localhost:8000/v1/productItem/
content-type: application/json

{
    "userId": "113577393364732277603"
}

###

# create new productItem
POST http://localhost:8000/v1/productItem/createProductItem
content-type: application/json

{
    "userId": "113577393364732277603",
    "ProductCategoryId":"615daecd7b17d504c37ba085",
    "itemName": "item 2",
    "imageUrl": "https://www.publicdomainpictures.net/pictures/10000/velka/1-1210009435EGmE.jpg",
    "quantity": 234,   
    "price": 123
}

###

PUT http://localhost:8000/v1/productItem/updateProductItem
content-type: application/json

{
    "itemToUpdate": "615daeb07b17d504c37ba082",
    "userId": "113577393364732277603",
    "ProductCategoryId":"615daef97b17d504c37ba08b",
    "itemName": "update1",
    "imageUrl": "update1",   
    "quantity": 234,   
    "price": 123
}

###

DELETE  http://localhost:8000/v1/productItem/deleteProductItem
content-type: application/json

{
    "itemToDelete": "6163cc8b85889b6f510ed09a"
}

###




